export * from './src/appointment.model';
export * from './src/configuration.model';
export * from './src/document.model';
export * from './src/lead.model';
export * from './src/message.model';
export * from './src/notification.model';
export * from './src/legal-process.model';
export * from './src/timeline-event.model';
export * from './src/user.model';
